## Set to the Postgres user you want to connect to; 'postgres' is the default user.
#spring.datasource.username=postgres
#spring.datasource.password=patrickTheGoat69
#spring.cloud.gcp.sql.database-name=spotifriends_db
## This value is formatted in the form: [gcp-project-id]:[region]:[instance-name]
#spring.cloud.gcp.sql.instance-connection-name=spotifriends:us-west2:spotifriends-db
## So app starts despite "table already exists" errors.
#spring.datasource.continue-on-error=true
## Enforces database initialization
#spring.datasource.initialization-mode=always
##spring.cloud.gcp.project-id=
##spring.cloud.gcp.credentials.location=file:/path/to/service-account.

app:
  datasource:
    jdbc-url: jdbc:postgresql:///{spotifriends_db}?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance={spotifriends:us-west2:spotifriends-db}:{spotifriends_db}
    username: postgres
    password: patrickTheGoat69